## Cv.2

In [17]:
import numpy as np
import sys, math

a = math.sqrt(2)
print(a, type(a), sys.getsizeof(a))
b = np.sqrt(2)
print(b, type(b), sys.getsizeof(b))

1.4142135623730951 <class 'float'> 24
1.4142135623730951 <class 'numpy.float64'> 32


In [44]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
display(a)
m = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
display(m)
n = np.array([[4, 5, 6], [7, 8, 9], [10, 11, 12]])
x = np.dot(m, n)
display(x)
display(x.shape)
display(x.size)
display(x.dtype)
display(x[:-1, :-1])
display(x[:, 1])

array([1, 2, 3, 4, 5])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array([[ 48,  54,  60],
       [111, 126, 141],
       [174, 198, 222]])

(3, 3)

9

dtype('int32')

array([[ 48,  54],
       [111, 126]])

array([ 54, 126, 198])

In [54]:
import numpy as np

a1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
display(a1)
v = np.array([1, 0, 10])
display(a1 + v)
display(a1 * v)
v = np.array([[1], [0], [10]])
display(a1 + v)
display(a1 * v)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array([[ 2,  2, 13],
       [ 5,  5, 16],
       [ 8,  8, 19]])

array([[ 1,  0, 30],
       [ 4,  0, 60],
       [ 7,  0, 90]])

array([[ 2,  3,  4],
       [ 4,  5,  6],
       [17, 18, 19]])

array([[ 1,  2,  3],
       [ 0,  0,  0],
       [70, 80, 90]])